<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_354e4"></div>
  <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/symbols/OANDA-EURUSD/" rel="noopener" target="_blank"><span class="blue-text">EURUSD Chart</span></a> by TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
  new TradingView.widget(
  {
  "width": 700,
  "height": 610,
  "symbol": "OANDA:EURUSD",
  "interval": "60",
  "timezone": "Asia/Bangkok",
  "theme": "light",
  "style": "1",
  "locale": "en",
  "toolbar_bg": "#f1f3f6",
  "enable_publishing": false,
  "allow_symbol_change": true,
  "container_id": "tradingview_354e4"
}
  );
  </script>
</div>
<!-- TradingView Widget END -->
